AllCops:
  DisabledByDefault: true

Style/FrozenStringLiteralComment:
  Enabled: true
  SafeAutoCorrect: true

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true

Layout/SpaceBeforeBlockBraces:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/ExtraSpacing:
  Enabled: true

Layout/IndentationWidth:
  Enabled: true

Layout/DefEndAlignment:
  Enabled: true

Style/HashSyntax:
  Enabled: true
